create table if not exists public.store_config (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.store_config enable row level security;

drop policy if exists "store_config_public_read" on public.store_config;
create policy "store_config_public_read"
on public.store_config
for select
to anon, authenticated
using (true);

drop policy if exists "store_config_owner_write" on public.store_config;
create policy "store_config_owner_write"
on public.store_config
for all
to authenticated
using (auth.jwt() ->> 'email' = current_setting('app.owner_email', true))
with check (auth.jwt() ->> 'email' = current_setting('app.owner_email', true));

-- Run this once in the Supabase SQL editor, replacing the email:
-- alter database postgres set app.owner_email = 'tu-correo@ejemplo.com';

create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  supplier_key text not null default 'vndrx',
  supplier_name text not null default 'VNDRX',
  status text not null default 'pendiente',
  payment text,
  payment_label text,
  subtotal numeric not null default 0,
  delivery numeric not null default 0,
  total numeric not null default 0,
  customer jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  extras jsonb not null default '{}'::jsonb,
  channel text not null default 'whatsapp',
  owner_test boolean not null default false
);

alter table public.orders enable row level security;

drop policy if exists "orders_customer_insert" on public.orders;
create policy "orders_customer_insert"
on public.orders
for insert
to anon, authenticated
with check (true);

drop policy if exists "orders_owner_read" on public.orders;
create policy "orders_owner_read"
on public.orders
for select
to authenticated
using (auth.jwt() ->> 'email' = current_setting('app.owner_email', true));

drop policy if exists "orders_owner_update" on public.orders;
create policy "orders_owner_update"
on public.orders
for update
to authenticated
using (auth.jwt() ->> 'email' = current_setting('app.owner_email', true))
with check (auth.jwt() ->> 'email' = current_setting('app.owner_email', true));

create table if not exists public.payment_proofs (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  created_at timestamptz not null default now(),
  file_path text not null,
  file_url text,
  status text not null default 'subido'
);

alter table public.payment_proofs enable row level security;

drop policy if exists "payment_proofs_customer_insert" on public.payment_proofs;
create policy "payment_proofs_customer_insert"
on public.payment_proofs
for insert
to anon, authenticated
with check (true);

drop policy if exists "payment_proofs_owner_read" on public.payment_proofs;
create policy "payment_proofs_owner_read"
on public.payment_proofs
for select
to authenticated
using (auth.jwt() ->> 'email' = current_setting('app.owner_email', true));

insert into storage.buckets (id, name, public)
values ('payment-proofs', 'payment-proofs', false)
on conflict (id) do nothing;

drop policy if exists "payment_proofs_storage_insert" on storage.objects;
create policy "payment_proofs_storage_insert"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'payment-proofs');

drop policy if exists "payment_proofs_storage_owner_read" on storage.objects;
create policy "payment_proofs_storage_owner_read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'payment-proofs'
  and auth.jwt() ->> 'email' = current_setting('app.owner_email', true)
);
